"""new db change and notion mig

Revision ID: 151c8863a58b
Revises: ae0dc6e2afe8
Create Date: 2026-03-17 18:41:38.813748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151c8863a58b'
down_revision: Union[str, Sequence[str], None] = 'ae0dc6e2afe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    phase_enum = sa.Enum('pre', 'during', 'post', name='phase_enum')
    phase_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('instructions', sa.Column('source', sa.String(), nullable=True, comment='Source url of the instruction'))
    op.add_column('instructions', sa.Column('phase', phase_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    phase_enum = sa.Enum('pre', 'during', 'post', name='phase_enum')
    op.drop_column('instructions', 'phase')
    op.drop_column('instructions', 'source')
    phase_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
