"""added royalties.py

Revision ID: 76f3e44aa5fe
Revises: 8c6caa6b3696
Create Date: 2026-03-22 16:10:40.429857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f3e44aa5fe'
down_revision: Union[str, Sequence[str], None] = '8c6caa6b3696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    format_enum = sa.Enum('mp3', 'wav', 'flac', 'aiff', 'other', name='format_enum')
    format_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('content', sa.Column('track_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'content', 'track', ['track_id'], ['track_id'])
    op.add_column('instructions', sa.Column('track_id', sa.UUID(), nullable=True))
    op.alter_column('instructions', 'instructions',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'instructions', 'track', ['track_id'], ['track_id'])
    op.add_column('track', sa.Column('track_title', sa.String(), nullable=True))
    op.add_column('track', sa.Column('format', format_enum, nullable=True))
    op.add_column('track', sa.Column('bitrate', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('sample_rate', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('version_subtitle', sa.String(), nullable=True))
    op.add_column('track', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('track', sa.Column('isrc', sa.String(), nullable=True))
    op.add_column('track', sa.Column('iwc', sa.String(), nullable=True))
    op.add_column('track', sa.Column('upc', sa.String(), nullable=True))
    op.add_column('track', sa.Column('lyrics', sa.Text(), nullable=True))
    op.add_column('track', sa.Column('bpm', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('key', sa.String(), nullable=True))
    op.add_column('track', sa.Column('genres', sa.JSON(), nullable=True))
    op.add_column('track', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('moods', sa.JSON(), nullable=True))
    op.add_column('track', sa.Column('keyword_tags', sa.JSON(), nullable=True))
    op.alter_column('track', 'track_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('track_content_id_fkey'), 'track', type_='foreignkey')
    op.drop_column('track', 'track_name')
    op.drop_column('track', 'content_id')
    op.drop_column('track', 'track_is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    format_enum = sa.Enum('mp3', 'wav', 'flac', 'aiff', 'other', name='format_enum')

    op.add_column('track', sa.Column('track_is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('track', sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('track', sa.Column('track_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('track_content_id_fkey'), 'track', 'content', ['content_id'], ['content_id'])
    op.alter_column('track', 'track_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('track', 'keyword_tags')
    op.drop_column('track', 'moods')
    op.drop_column('track', 'duration_seconds')
    op.drop_column('track', 'genres')
    op.drop_column('track', 'key')
    op.drop_column('track', 'bpm')
    op.drop_column('track', 'lyrics')
    op.drop_column('track', 'upc')
    op.drop_column('track', 'iwc')
    op.drop_column('track', 'isrc')
    op.drop_column('track', 'release_date')
    op.drop_column('track', 'version_subtitle')
    op.drop_column('track', 'sample_rate')
    op.drop_column('track', 'bitrate')
    op.drop_column('track', 'format')
    op.drop_column('track', 'track_title')
    op.drop_constraint(None, 'instructions', type_='foreignkey')
    op.alter_column('instructions', 'instructions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('instructions', 'track_id')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'track_id')
    format_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
