"""instruction and action knowledge change

Revision ID: 8c6caa6b3696
Revises: b7a2f6c91d1a
Create Date: 2026-03-18 19:54:38.567286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6caa6b3696'
down_revision: Union[str, Sequence[str], None] = 'b7a2f6c91d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_resources',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Workspace scope; future change may convert this to a foreign key.'),
    sa.Column('canonical_key', sa.String(), nullable=False, comment='Stable identifier used to group immutable versions of the same resource.'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_resource_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('BOOK', 'DOCUMENT', 'GUIDE', 'FRAMEWORK', 'CASE_STUDY', 'OTHER', name='knowledge_resource_category_enum'), nullable=False),
    sa.Column('resource_format', sa.Enum('PROMPT', 'URL', 'TEXT', name='knowledge_resource_format_enum'), nullable=False),
    sa.Column('ingestion_method', sa.Enum('MANUAL', name='knowledge_resource_ingestion_method_enum'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON array of tags. Example: ["seo", "retention", "positioning"]'),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='Canonical text representation for URL/text/prompt resources.'),
    sa.Column('retrieval_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible metadata for future strategy mapping and retrieval filters.'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_resource_id'], ['knowledge_resources.resource_id'], ),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('workspace_id', 'canonical_key', 'version', name='uq_knowledge_resource_workspace_key_version')
    )
    op.create_index(op.f('ix_knowledge_resources_resource_id'), 'knowledge_resources', ['resource_id'], unique=False)
    op.create_table('knowledge_resource_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_provider', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('embedding_reference', sa.String(), nullable=True, comment='External vector ID/reference if vectors are stored outside this table.'),
    sa.Column('retrieval_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Chunk-level retrieval metadata (e.g., section, heading, page range).'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['knowledge_resources.resource_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('resource_id', 'chunk_index', name='uq_knowledge_resource_chunk_index')
    )
    op.create_index(op.f('ix_knowledge_resource_chunks_chunk_id'), 'knowledge_resource_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_resource_chunks_resource_id'), 'knowledge_resource_chunks', ['resource_id'], unique=False)
    op.drop_constraint(op.f('action_instruction_id_fkey'), 'action', type_='foreignkey')
    op.drop_column('action', 'instruction_id')
    op.add_column('instructions', sa.Column('source_media', sa.String(), nullable=True, comment='Source media of the instruction'))
    op.alter_column('instructions', 'source',
               existing_type=sa.VARCHAR(),
               comment='Source url of the instruction',
               existing_nullable=True)
    op.drop_column('instructions', 'sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of sources - can be URLs, file paths, or base64 encoded media'))
    op.alter_column('instructions', 'source',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Source url of the instruction',
               existing_nullable=True)
    op.drop_column('instructions', 'source_media')
    op.add_column('action', sa.Column('instruction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('action_instruction_id_fkey'), 'action', 'instructions', ['instruction_id'], ['instruction_id'])
    op.drop_index(op.f('ix_knowledge_resource_chunks_resource_id'), table_name='knowledge_resource_chunks')
    op.drop_index(op.f('ix_knowledge_resource_chunks_chunk_id'), table_name='knowledge_resource_chunks')
    op.drop_table('knowledge_resource_chunks')
    op.drop_index(op.f('ix_knowledge_resources_resource_id'), table_name='knowledge_resources')
    op.drop_table('knowledge_resources')
    # ### end Alembic commands ###
