"""first

Revision ID: 98a9e55831ed
Revises: 
Create Date: 2026-03-16 18:01:59.458310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98a9e55831ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.Column('engagement_phase', sa.Enum('awareness', 'interest', 'consideration', 'intent', 'evaluation', 'purchase', name='engagement_phase_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_content_content_id'), 'content', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_name'), 'content', ['name'], unique=True)
    op.create_table('frequencies',
    sa.Column('frequency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('frequency_unit', sa.String(), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('time_period', sa.Enum('definite', 'indefinite', name='time_period_enum'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('frequency_type', sa.Enum('recurring', 'one-time', name='frequency_type_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('frequency_id')
    )
    op.create_index(op.f('ix_frequencies_frequency_id'), 'frequencies', ['frequency_id'], unique=False)
    op.create_index(op.f('ix_frequencies_name'), 'frequencies', ['name'], unique=True)
    op.create_table('instagram_hashtags',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=True, comment='The hashtag used in the post'),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('instagram_media_insights',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('media_id', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions_count', sa.Integer(), nullable=True),
    sa.Column('saved', sa.Integer(), nullable=True),
    sa.Column('reels_plays', sa.Integer(), nullable=True),
    sa.Column('ig_reels_avg_watch_time', sa.Interval(), nullable=True),
    sa.Column('ig_reels_skip_rate', sa.Integer(), nullable=True),
    sa.Column('crossposted_views', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True, comment='Number of likes, saves, comments, and shares on the reel, minus the number of unlikes, unsaves, and deleted comments'),
    sa.Column('navigation', sa.Integer(), nullable=True, comment='This is the total number of actions taken from your story. These are made up of metrics like exited, forward, back and next story.'),
    sa.Column('story_navigation_action_type', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Break down results by navigation action taken by the viewer upon viewing the media within the native app'),
    sa.Column('plays', sa.Integer(), nullable=True, comment='Number of times the reels starts to play after an impression is already counted.'),
    sa.Column('profile_activity', sa.Integer(), nullable=True, comment='The number of actions people take when they visit your profile after engaging with your post'),
    sa.Column('action_type', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='The type of action taken by the user'),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('follower_growth', sa.Integer(), nullable=True),
    sa.Column('profile_links_taps', sa.Integer(), nullable=True),
    sa.Column('audience_demographics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('instagram_profile_insights',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions_count', sa.Integer(), nullable=True),
    sa.Column('profile_views_count', sa.Integer(), nullable=True),
    sa.Column('medica_count', sa.Integer(), nullable=True),
    sa.Column('follower_growth', sa.Integer(), nullable=True),
    sa.Column('profile_links_taps', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('platforms',
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('DISTRIBUTION', 'ADMIN', 'TOOL', 'PROMOTION', 'ANALYTICS', name='platform_type'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('account_data', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_index(op.f('ix_platforms_platform_id'), 'platforms', ['platform_id'], unique=False)
    op.create_table('tiktok_media_insights',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=True, comment='The ID of the TikTok media'),
    sa.Column('cover_image_url', sa.String(), nullable=True, comment="A CDN link for the video's cover image. "),
    sa.Column('video_description', sa.String(), nullable=True, comment='The description of the video.'),
    sa.Column('duration', sa.Interval(), nullable=True, comment='The duration of the video in seconds.'),
    sa.Column('title', sa.String(), nullable=True, comment='The title of the video.'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='The number of likes the video has received.'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='The number of comments the video has received.'),
    sa.Column('share_count', sa.Integer(), nullable=True, comment='The number of shares the video has received.'),
    sa.Column('views_count', sa.Integer(), nullable=True, comment='The number of views the video has received.'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('tiktok_profile_insights',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True, comment='The URL of the TikTok profile avatar'),
    sa.Column('bio_description', sa.String(), nullable=True, comment='The bio description of the TikTok profile'),
    sa.Column('profile_deep_link', sa.String(), nullable=True, comment="The link to user's TikTok profile page"),
    sa.Column('username', sa.String(), nullable=True, comment='The username of the TikTok profile'),
    sa.Column('followers_count', sa.Integer(), nullable=True, comment='The number of followers the profile has.'),
    sa.Column('following_count', sa.Integer(), nullable=True, comment='The number of accounts the profile is following.'),
    sa.Column('likes_count', sa.Integer(), nullable=True, comment='The number of likes the profile has.'),
    sa.Column('videos_count', sa.Integer(), nullable=True, comment='The number of videos the profile has.'),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('twitter_x_content_insights',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='The content of the post'),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('twitter_x_mentions',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('mentions', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='The mentions in the post'),
    sa.Column('owner', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='The owner of the post'),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('twitter_x_public_metrics',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('bookmark_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('twitter_x_user_metrics',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('engagements', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('youtube_channel_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('dimensions', sa.ARRAY(sa.String()), nullable=True, comment='The dimension of the report'),
    sa.Column('filters', sa.ARRAY(sa.String()), nullable=True, comment='The filters of the report'),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='The result of the report'),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('youtube_video_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('dimensions', sa.ARRAY(sa.String()), nullable=True, comment='The dimension of the report'),
    sa.Column('filters', sa.ARRAY(sa.String()), nullable=True, comment='The filters of the report'),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='The result of the report'),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Data returned from the api'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('bluesky_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('bluesky_content_url', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('bluesky_content_is_active', sa.Boolean(), nullable=True),
    sa.Column('bluesky_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('instagram_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('bio_url', sa.String(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('total_media_count', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('instagram_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('post_type', sa.Enum('PHOTO', 'VIDEO', 'CAROUSEL', 'TEXT', 'GIF', 'OTHER', name='media_type_enum'), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('saves_count', sa.Integer(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('instagram_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('instagram_reel',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('instagram_reel_url', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('saves_count', sa.Integer(), nullable=True),
    sa.Column('instagram_reel_is_active', sa.Boolean(), nullable=True),
    sa.Column('instagram_reel_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('instagram_story',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('instagram_story_is_active', sa.Boolean(), nullable=True),
    sa.Column('instagram_story_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('instructions',
    sa.Column('instruction_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('frequency_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('dependency_instruction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_instruction_id'], ['instructions.instruction_id'], ),
    sa.ForeignKeyConstraint(['frequency_id'], ['frequencies.frequency_id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('instruction_id')
    )
    op.create_index(op.f('ix_instructions_instruction_id'), 'instructions', ['instruction_id'], unique=False)
    op.create_index(op.f('ix_instructions_name'), 'instructions', ['name'], unique=True)
    op.create_table('reddit_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('reddit_content_url', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reddit_content_is_active', sa.Boolean(), nullable=True),
    sa.Column('reddit_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('success_metrics',
    sa.Column('success_metrics_id', sa.UUID(), nullable=False),
    sa.Column('success_metrics_name', sa.String(), nullable=True),
    sa.Column('success_metrics_description', sa.String(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('target_value_unit', sa.String(), nullable=True),
    sa.Column('success_metrics_is_active', sa.Boolean(), nullable=True),
    sa.Column('success_metrics_notes', sa.String(), nullable=True),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('success_metrics_id')
    )
    op.create_index(op.f('ix_success_metrics_success_metrics_id'), 'success_metrics', ['success_metrics_id'], unique=False)
    op.create_table('thread_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('thread_content_url', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('saves_count', sa.Integer(), nullable=True),
    sa.Column('thread_content_is_active', sa.Boolean(), nullable=True),
    sa.Column('thread_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('tiktok_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('pinned_post_id', sa.JSON(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('list_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('verified_status', sa.Enum('verified', 'not_verified', 'pending', name='verified_status'), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('twitter_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('pinned_post_id', sa.JSON(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('list_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('verified_status', sa.Enum('verified', 'not_verified', 'pending', name='verified_status'), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('twitter_x_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('twitter_x_content_url', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('twitter_x_content_is_active', sa.Boolean(), nullable=True),
    sa.Column('twitter_x_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('youtube_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('pinned_post_id', sa.JSON(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('list_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('verified_status', sa.Enum('verified', 'not_verified', 'pending', name='verified_status'), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('youtube_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('youtube_content_url', sa.String(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('youtube_content_is_active', sa.Boolean(), nullable=True),
    sa.Column('youtube_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('youtube_short',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('youtube_short_url', sa.String(), nullable=True),
    sa.Column('youtube_short_is_active', sa.Boolean(), nullable=True),
    sa.Column('youtube_short_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('action',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='action_status_enum'), nullable=True),
    sa.Column('next_action_due_date', sa.DateTime(), nullable=True),
    sa.Column('action_is_active', sa.Boolean(), nullable=True),
    sa.Column('action_notes', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('instruction_id', sa.UUID(), nullable=True),
    sa.Column('dependency_action_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.ForeignKeyConstraint(['dependency_action_id'], ['action.action_id'], ),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.instruction_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_action_action_id'), 'action', ['action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_action_id'), table_name='action')
    op.drop_table('action')
    op.drop_table('youtube_short')
    op.drop_table('youtube_content')
    op.drop_table('youtube_accounts')
    op.drop_table('twitter_x_content')
    op.drop_table('twitter_accounts')
    op.drop_table('tiktok_accounts')
    op.drop_table('thread_content')
    op.drop_index(op.f('ix_success_metrics_success_metrics_id'), table_name='success_metrics')
    op.drop_table('success_metrics')
    op.drop_table('reddit_content')
    op.drop_index(op.f('ix_instructions_name'), table_name='instructions')
    op.drop_index(op.f('ix_instructions_instruction_id'), table_name='instructions')
    op.drop_table('instructions')
    op.drop_table('instagram_story')
    op.drop_table('instagram_reel')
    op.drop_table('instagram_content')
    op.drop_table('instagram_accounts')
    op.drop_table('bluesky_content')
    op.drop_table('youtube_video_reports')
    op.drop_table('youtube_channel_reports')
    op.drop_table('twitter_x_user_metrics')
    op.drop_table('twitter_x_public_metrics')
    op.drop_table('twitter_x_mentions')
    op.drop_table('twitter_x_content_insights')
    op.drop_table('tiktok_profile_insights')
    op.drop_table('tiktok_media_insights')
    op.drop_index(op.f('ix_platforms_platform_id'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_table('instagram_profile_insights')
    op.drop_table('instagram_media_insights')
    op.drop_table('instagram_hashtags')
    op.drop_index(op.f('ix_frequencies_name'), table_name='frequencies')
    op.drop_index(op.f('ix_frequencies_frequency_id'), table_name='frequencies')
    op.drop_table('frequencies')
    op.drop_index(op.f('ix_content_name'), table_name='content')
    op.drop_index(op.f('ix_content_content_id'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
