"""for notion

Revision ID: ae0dc6e2afe8
Revises: c91b69de188a
Create Date: 2026-03-17 03:44:35.739946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae0dc6e2afe8'
down_revision: Union[str, Sequence[str], None] = 'c91b69de188a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_name'), table_name='content')
    op.add_column('frequencies', sa.Column('instruction_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_frequencies_name'), table_name='frequencies')
    op.create_foreign_key(None, 'frequencies', 'instructions', ['instruction_id'], ['instruction_id'])
    op.drop_index(op.f('ix_instructions_name'), table_name='instructions')
    op.drop_constraint(op.f('instructions_frequency_id_fkey'), 'instructions', type_='foreignkey')
    op.drop_column('instructions', 'frequency_id')
    op.alter_column('twitter_x_user_metrics', 'impressions',
               existing_type=sa.INTEGER(),
               comment='The number of impressions of the post',
               existing_nullable=True)
    op.alter_column('twitter_x_user_metrics', 'engagements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='The engagements of the post',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_x_user_metrics', 'engagements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='The engagements of the post',
               existing_nullable=True)
    op.alter_column('twitter_x_user_metrics', 'impressions',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='The number of impressions of the post',
               existing_nullable=True)
    op.add_column('instructions', sa.Column('frequency_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('instructions_frequency_id_fkey'), 'instructions', 'frequencies', ['frequency_id'], ['frequency_id'])
    op.create_index(op.f('ix_instructions_name'), 'instructions', ['name'], unique=True)
    op.drop_constraint(None, 'frequencies', type_='foreignkey')
    op.create_index(op.f('ix_frequencies_name'), 'frequencies', ['name'], unique=True)
    op.drop_column('frequencies', 'instruction_id')
    op.create_index(op.f('ix_content_name'), 'content', ['name'], unique=True)
    # ### end Alembic commands ###
