"""db instruction change

Revision ID: f81541398d0c
Revises: 98b3eab0e4bc
Create Date: 2026-03-17 23:29:36.772134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81541398d0c'
down_revision: Union[str, Sequence[str], None] = '98b3eab0e4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=True),
    sa.Column('track_description', sa.String(), nullable=True),
    sa.Column('track_is_active', sa.Boolean(), nullable=True),
    sa.Column('track_notes', sa.String(), nullable=True),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_index(op.f('ix_track_track_id'), 'track', ['track_id'], unique=False)
    op.add_column('instructions', sa.Column('sources', sa.JSON(), nullable=True, comment='List of sources - can be URLs, file paths, or base64 encoded media'))
    op.drop_column('instructions', 'source')
    op.add_column('youtube_content', sa.Column('youtube_content_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'youtube_content', ['youtube_content_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube_content', type_='unique')
    op.drop_column('youtube_content', 'youtube_content_id')
    op.add_column('instructions', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Source url of the instruction'))
    op.drop_column('instructions', 'sources')
    op.drop_index(op.f('ix_track_track_id'), table_name='track')
    op.drop_table('track')
    # ### end Alembic commands ###
